targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/dto/**.dart
          - lib/providers/**.dart
        options:
          build_extensions:
            '^lib/dto/{{}}.dart': 'lib/dto/generated/{{}}.g.dart'
            '^lib/providers/{{}}.dart': 'lib/providers/generated/{{}}.g.dart'
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/dto/{{}}.dart': 'lib/dto/generated/{{}}.freezed.dart'
      riverpod_generator|riverpod_generator:
        options:
          '^lib/providers/{{}}.dart': 'lib/providers/generated/{{}}.g.dart'