targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/dto/**.dart
        options:
          build_extensions:
            '^lib/dto/{{}}.dart': 'lib/dto/generated/{{}}.g.dart'
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/dto/{{}}.dart': 'lib/dto/generated/{{}}.freezed.dart'